"""Generate structured emergency operations reports."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from assistant.config import CITY_NAME, REPORTS_DIR
from assistant.context.platform_context import build_platform_snapshot
from assistant.tools.operations import summarize_shortages


def generate_emergency_report(
    incident_title: str = "Water Supply Emergency Assessment",
    save: bool = True,
) -> str:
    snapshot = build_platform_snapshot()
    risks = snapshot.get("zone_risks", [])
    routes = snapshot.get("tanker_routes", [])
    forecasts = snapshot.get("forecasts", {})
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    critical = [r for r in risks if r.get("risk_level") in ("critical", "high")]
    max_risk = max(risks, key=lambda x: x.get("risk_score", 0)) if risks else None

    lines = [
        f"# EMERGENCY REPORT: {incident_title}",
        f"**Jurisdiction:** {CITY_NAME}",
        f"**Generated:** {now}",
        f"**Classification:** OPERATIONAL — FOR AUTHORIZED PERSONNEL",
        "",
        "---",
        "",
        "## 1. Executive Summary",
        "",
    ]

    if critical:
        lines.append(
            f"This report identifies **{len(critical)} zone(s)** under elevated water stress. "
            f"Highest risk: **{max_risk['zone']}** at {max_risk['risk_score']:.1f}% "
            f"(gap {max_risk.get('gap_liters', 0):,.0f} liters/day)."
        )
    else:
        lines.append(
            "Current modeling indicates no critical city-wide shortage. "
            "Continue standard monitoring and preventive maintenance."
        )

    lines.extend(["", "## 2. Zone Risk Status", "", summarize_shortages(snapshot), ""])
    lines.extend(["", "## 3. Demand Forecast (7-day)", ""])

    for zone, fc in list(forecasts.items())[:5]:
        if isinstance(fc, dict) and "forecast" in fc:
            lines.append(f"### {zone}")
            for d in fc["forecast"][:3]:
                lines.append(f"- {d['date']}: {d['water_demand_liters']:,} L/day")
            lines.append("")

    lines.extend(["", "## 4. Recommended Response Actions", ""])
    if critical:
        lines.append("1. Activate emergency groundwater reserves in affected zones.")
        lines.append("2. Deploy tankers per optimized routing plan below.")
        lines.append("3. Issue public conservation advisory (SMS, PA systems).")
        lines.append("4. Reduce non-essential industrial allocation by 10–15%.")
        lines.append("5. Increase reservoir pumping; monitor pressure sensors hourly.")
    else:
        lines.append("1. Maintain standard distribution schedules.")
        lines.append("2. Pre-position tankers in highest-consumption zones as precaution.")

    lines.extend(["", "## 5. Tanker Deployment Plan", ""])
    if routes and "error" not in routes[0]:
        for i, r in enumerate(routes, 1):
            lines.append(
                f"- **Route {i}** ({r.get('depot', 'depot')}): "
                f"{r.get('distance_km', 0)} km, {r.get('stops', 0)} stops, "
                f"estimated delivery demand {r.get('demand_liters', 0):,.0f} L"
            )
            for name in r.get("stop_names", [])[:6]:
                lines.append(f"  - {name}")
    else:
        lines.append("- Tanker routes unavailable; run GIS dashboard to optimize.")

    lines.extend(
        [
            "",
            "## 6. Anomalies & Sensors",
            "",
            str(snapshot.get("anomalies", "No anomaly data")),
            "",
            "## 7. Sign-off",
            "",
            "| Role | Name | Time |",
            "|------|------|------|",
            "| Operations Lead | __________ | ______ |",
            "| City Engineer | __________ | ______ |",
            "",
            "*Report auto-generated by AquaOps AI Assistant.*",
        ]
    )

    report = "\n".join(lines)
    if save:
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        fname = REPORTS_DIR / f"emergency_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"
        fname.write_text(report, encoding="utf-8")
    return report
