city_id: delhi-ncr

edge_gateways:
  - id: edge-north-01
    zone_code: north-delhi
    mqtt_client_id: edge-north-01
  - id: edge-south-01
    zone_code: south-delhi
    mqtt_client_id: edge-south-01
  - id: edge-central-01
    zone_code: central-delhi
    mqtt_client_id: edge-central-01
  - id: edge-east-01
    zone_code: east-delhi
    mqtt_client_id: edge-east-01
  - id: edge-west-01
    zone_code: west-delhi
    mqtt_client_id: edge-west-01

devices:
  - device_id: FM-NRD-001
    device_type: flow_meter
    zone_code: north-delhi
    edge_gateway_id: edge-north-01
    publish_interval_sec: 5

  - device_id: FM-STH-001
    device_type: flow_meter
    zone_code: south-delhi
    edge_gateway_id: edge-south-01
    publish_interval_sec: 5

  - device_id: RSV-CTR-01
    device_type: reservoir_level
    zone_code: central-delhi
    edge_gateway_id: edge-central-01
    publish_interval_sec: 10

  - device_id: PRS-EAST-12
    device_type: pressure_sensor
    zone_code: east-delhi
    edge_gateway_id: edge-east-01
    publish_interval_sec: 3

  - device_id: PRS-WEST-05
    device_type: pressure_sensor
    zone_code: west-delhi
    edge_gateway_id: edge-west-01
    publish_interval_sec: 3

  - device_id: GW-WEST-03
    device_type: groundwater
    zone_code: west-delhi
    edge_gateway_id: edge-west-01
    publish_interval_sec: 30
